version: "3"

services:
  predictor:
    build: .
    image: iris_pred_yl:latest
    ports:
      - "8080:8080"
    volumes:
      - ./test_dir:/opt/ml
    entrypoint: serve
    
#  redis:
#    image: "redis:alpine"
#    ports:
#      - "6379:6379"